/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/autostrm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["autostrm_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/c115/auto-cid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auto_cid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/c115/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["offline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/c115/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["parse_url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/c115/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/c115/snap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["snap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/c115/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["test_cookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["catalog_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["catalog_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/transfer-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["catalog_transfer_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/cleanup/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cleanup_summary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config"];
        put: operations["put_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/gaps/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["gaps_summary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["libraries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/libraries/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scan_library"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/libraries/strm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_strm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/manage/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/manage/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview_move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/manage/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_undo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/manage/undo/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exec_undo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/posters/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/posters/detect-mismatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["detect_mismatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/posters/fix-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fix_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/posters/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_schedules"];
        put?: never;
        post: operations["create_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_schedule"];
        post?: never;
        delete: operations["delete_schedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/schedules/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/system/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["system_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["demo_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/users/{id}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user_policy"];
        put: operations["update_user_policy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppLogEntry: {
            /** Format: date-time */
            created_at: string;
            detail: unknown;
            /** Format: int64 */
            id: number;
            level: string;
            message: string;
        };
        AutostrmLibraryStat: {
            lib: string;
            /** Format: int64 */
            seen: number;
            /** Format: int64 */
            unmatched: number;
        };
        AutostrmSeenStats: {
            /** Format: date-time */
            last_seen_at?: string | null;
            /** Format: int64 */
            libraries: number;
            /** Format: int64 */
            total: number;
        };
        AutostrmSnapshot: {
            libraries: components["schemas"]["AutostrmLibraryStat"][];
            seen: components["schemas"]["AutostrmSeenStats"];
            unmatched: components["schemas"]["AutostrmUnmatchedStats"];
        };
        AutostrmStatusResponse: {
            complete_business_port: boolean;
            libraries: components["schemas"]["AutostrmLibraryStat"][];
            meta: components["schemas"]["InsightMeta"];
            ok: boolean;
            seen: components["schemas"]["AutostrmSeenStats"];
            todos: components["schemas"]["InsightTodo"][];
            unmatched: components["schemas"]["AutostrmUnmatchedStats"];
            warnings: string[];
        };
        AutostrmUnmatchedStats: {
            /** Format: date-time */
            first_created_at?: string | null;
            /** Format: date-time */
            last_updated_at?: string | null;
            /** Format: int64 */
            libraries: number;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            without_emby_id: number;
        };
        C115AutoCidRequest: {
            max_depth?: number | null;
        };
        C115AutoCidResponse: {
            current: {
                [key: string]: string;
            };
            matches: {
                [key: string]: components["schemas"]["C115CidMatch"][];
            };
            ok: boolean;
            scanned: number;
        };
        C115CidMatch: {
            cid: string;
            path: string;
        };
        C115DirEntry: {
            cid: string;
            name: string;
        };
        C115OfflineRequest: {
            cid?: string | null;
            label?: string | null;
            lib?: string | null;
            url: string;
        };
        C115OfflineResponse: {
            cid: string;
            info_hash?: string | null;
            lib?: string | null;
            msg: string;
            ok: boolean;
        };
        C115ParseResponse: {
            receive_code?: string | null;
            share?: string | null;
        };
        C115SaveRequest: {
            cid?: string | null;
            file_ids?: string[] | null;
            label?: string | null;
            lib?: string | null;
            pwd?: string | null;
            url: string;
        };
        C115SaveResponse: {
            cid: string;
            count: number;
            lib?: string | null;
            msg: string;
            ok: boolean;
            share: string;
            title?: string | null;
        };
        C115SnapFile: {
            id?: string | null;
            is_dir: boolean;
            name: string;
            /** Format: int64 */
            size: number;
        };
        C115SnapRequest: {
            file_ids?: string[] | null;
            pwd?: string | null;
            url: string;
        };
        C115SnapResponse: {
            file_size?: unknown;
            files: components["schemas"]["C115SnapFile"][];
            ok: boolean;
            rc?: string | null;
            share: string;
            share_title?: string | null;
        };
        C115TestResponse: {
            ok: boolean;
            uid: string;
            used: string;
        };
        CatalogC115OfflinePayload: {
            cid?: string | null;
            label?: string | null;
            lib?: string | null;
            url: string;
        };
        CatalogC115OfflinePlan: {
            endpoint: string;
            method: string;
            payload: components["schemas"]["CatalogC115OfflinePayload"];
            protocol: string;
        };
        CatalogC115SavePayload: {
            cid?: string | null;
            label?: string | null;
            lib?: string | null;
            pwd?: string | null;
            url: string;
        };
        CatalogC115SavePlan: {
            endpoint: string;
            method: string;
            payload: components["schemas"]["CatalogC115SavePayload"];
            receive_code?: string | null;
            share: string;
        };
        CatalogInsight: {
            available: boolean;
            /** Format: int64 */
            duplicate_links: number;
            /** Format: int64 */
            duplicate_names: number;
            /** Format: int64 */
            ed2k: number;
            /** Format: int64 */
            magnet: number;
            /** Format: int64 */
            other: number;
            /** Format: int64 */
            packages: number;
            /** Format: int64 */
            share115: number;
            /** Format: int64 */
            total: number;
        };
        CatalogItem: {
            is_pkg: boolean;
            link: string;
            link_type: string;
            name: string;
            rc?: string | null;
            share?: string | null;
            sheet: string;
            transfer: boolean;
        };
        CatalogSearchQuery: {
            /** Format: int64 */
            limit?: number | null;
            link_type?: string | null;
            q: string;
        };
        CatalogSearchResponse: {
            items: components["schemas"]["CatalogItem"][];
            total: number;
            truncated: boolean;
        };
        CatalogStatsResponse: {
            available: boolean;
            /** Format: int64 */
            packages: number;
            /** Format: int64 */
            total: number;
        };
        /** @enum {string} */
        CatalogTransferAction: "save_share" | "offline_download" | "unsupported";
        CatalogTransferPlanItem: {
            is_pkg?: boolean | null;
            link: string;
            link_type?: string | null;
            name?: string | null;
            rc?: string | null;
            share?: string | null;
            sheet?: string | null;
        };
        CatalogTransferPlanRequest: {
            cid?: string | null;
            is_pkg?: boolean | null;
            item?: null | components["schemas"]["CatalogTransferPlanItem"];
            label?: string | null;
            lib?: string | null;
            link?: string | null;
            link_type?: string | null;
            name?: string | null;
            pwd?: string | null;
            rc?: string | null;
            share?: string | null;
            sheet?: string | null;
        };
        CatalogTransferPlanResponse: {
            action: components["schemas"]["CatalogTransferAction"];
            is_pkg: boolean;
            label?: string | null;
            link_type: string;
            offline?: null | components["schemas"]["CatalogC115OfflinePlan"];
            ok: boolean;
            save?: null | components["schemas"]["CatalogC115SavePlan"];
            target: components["schemas"]["CatalogTransferTarget"];
            transfer: boolean;
            unsupported?: null | components["schemas"]["CatalogUnsupportedPlan"];
        };
        CatalogTransferTarget: {
            cid?: string | null;
            lib?: string | null;
        };
        CatalogUnsupportedPlan: {
            link: string;
            reason: string;
        };
        CleanupSummaryResponse: {
            autostrm: components["schemas"]["AutostrmSnapshot"];
            catalog: components["schemas"]["CatalogInsight"];
            complete_business_port: boolean;
            logs: components["schemas"]["LogInsight"];
            meta: components["schemas"]["InsightMeta"];
            ok: boolean;
            schedules: components["schemas"]["ScheduleInsight"];
            strm: components["schemas"]["StrmReadOnlyOverview"];
            task_history: components["schemas"]["TaskHistorySummary"];
            todos: components["schemas"]["InsightTodo"][];
            warnings: string[];
        };
        ConfigResponse: {
            settings: {
                [key: string]: unknown;
            };
        };
        ConfigUpdateRequest: {
            settings: {
                [key: string]: unknown;
            };
        };
        DatabaseSummary: {
            configured: boolean;
            current_database?: string | null;
            idle_connections: number;
            /** Format: int32 */
            pool_size: number;
            server_version?: string | null;
            status: string;
            url: string;
            warning?: string | null;
        };
        DeleteScheduleResponse: {
            ok: boolean;
        };
        DemoTaskRequest: {
            label?: string | null;
            /** Format: int64 */
            seconds?: number | null;
        };
        DiskSummary: {
            /** Format: int64 */
            available_bytes: number;
            filesystem: string;
            mount_point: string;
            /** Format: int64 */
            total_bytes: number;
            /** Format: int64 */
            used_bytes: number;
            /** Format: double */
            used_percent?: number | null;
        };
        EmbyLibrary: {
            id?: string | null;
            name: string;
            paths: string[];
            type: string;
        };
        ExtensionCount: {
            /** Format: int64 */
            count: number;
            extension: string;
        };
        GapsSummaryResponse: {
            autostrm: components["schemas"]["AutostrmSnapshot"];
            catalog: components["schemas"]["CatalogInsight"];
            complete_business_port: boolean;
            meta: components["schemas"]["InsightMeta"];
            ok: boolean;
            strm: components["schemas"]["StrmReadOnlyOverview"];
            task_history: components["schemas"]["TaskHistorySummary"];
            todos: components["schemas"]["InsightTodo"][];
            warnings: string[];
        };
        HealthResponse: {
            database: string;
            status: string;
            version: string;
        };
        HostMetrics: {
            arch: string;
            load_average?: null | components["schemas"]["LoadAverage"];
            memory?: null | components["schemas"]["MemorySummary"];
            os: string;
            /** Format: int32 */
            process_id: number;
        };
        InsightMeta: {
            coverage: string[];
            /** Format: date-time */
            generated_at: string;
            limitations: string[];
            readonly: boolean;
            source: string[];
        };
        InsightTodo: {
            area: string;
            /** Format: int64 */
            count: number;
            message: string;
            severity: string;
            source: string;
        };
        LibrariesResponse: {
            libraries: components["schemas"]["EmbyLibrary"][];
        };
        LoadAverage: {
            /** Format: double */
            fifteen: number;
            /** Format: double */
            five: number;
            /** Format: double */
            one: number;
        };
        LogInsight: {
            /** Format: int64 */
            errors_7d: number;
            /** Format: date-time */
            last_error_at?: string | null;
            /** Format: int64 */
            warnings_7d: number;
        };
        LogListQuery: {
            level?: string | null;
            /** Format: int64 */
            limit?: number | null;
        };
        LogListResponse: {
            logs: components["schemas"]["AppLogEntry"][];
            total: number;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        LoginResponse: {
            csrf: string;
            ok: boolean;
            token: string;
            username: string;
        };
        ManageDeleteRequest: {
            folder: string;
            item_id?: string | null;
            lib: string;
            reason?: string | null;
        };
        ManageMoveRequest: {
            from_folder: string;
            from_lib: string;
            item_id?: string | null;
            reason?: string | null;
            to_folder?: string | null;
            to_lib: string;
        };
        ManagePreviewResult: {
            dry_run: boolean;
            message: string;
            next_steps: string[];
            ok: boolean;
            operation: string;
            planned_paths: string[];
            preview: boolean;
            warnings: string[];
        };
        MeResponse: {
            authenticated: boolean;
            csrf?: string | null;
            username?: string | null;
        };
        MemorySummary: {
            /** Format: int64 */
            available_bytes: number;
            /** Format: int64 */
            total_bytes: number;
            /** Format: double */
            used_percent: number;
        };
        PathStatus: {
            disk?: null | components["schemas"]["DiskSummary"];
            exists: boolean;
            expected_kind: string;
            is_dir: boolean;
            is_file: boolean;
            key: string;
            label: string;
            path: string;
            readable?: boolean | null;
            warnings: string[];
            writable_hint?: boolean | null;
        };
        PlaceholderResponse: {
            message: string;
            module: string;
            ok: boolean;
        };
        PosterApplyRequest: {
            id: string;
            name?: string | null;
            tmdb: string;
            type: string;
        };
        PosterApplyResponse: {
            /** Format: int32 */
            apply_status: number;
            /** Format: int32 */
            image_download_status?: number | null;
            name: string;
            ok: boolean;
            poster: boolean;
            /** Format: int32 */
            refresh_status: number;
            tmdb: string;
        };
        PosterDetectRequest: {
            include_missing_primary?: boolean | null;
            lib?: string | null;
            limit?: number | null;
        };
        PosterDetectResponse: {
            items: components["schemas"]["PosterSignalItem"][];
            mismatch_total: number;
            missing_primary_total: number;
            ok: boolean;
            scanned_items: number;
            scanned_libraries: number;
            total: number;
            truncated: boolean;
            warnings: string[];
        };
        PosterFixBatchRequest: {
            ids: string[];
            type: string;
        };
        PosterFixBatchResult: {
            ok_count: number;
            results: components["schemas"]["PosterFixOneResult"][];
            total: number;
        };
        PosterFixOneResult: {
            err: string;
            id: string;
            name: string;
            ok: boolean;
            tmdb?: string | null;
        };
        PosterSearchCandidate: {
            img: string;
            name: string;
            overview: string;
            tmdb: string;
            /** Format: int32 */
            year?: number | null;
        };
        PosterSearchRequest: {
            id: string;
            limit?: number | null;
            name: string;
            type: string;
        };
        PosterSearchResponse: {
            candidates: components["schemas"]["PosterSearchCandidate"][];
            ok: boolean;
        };
        PosterSignal: {
            kind: string;
            message: string;
            severity: string;
        };
        PosterSignalItem: {
            declared_tmdb?: string | null;
            emby_name: string;
            folder: string;
            folder_clean: string;
            has_poster: boolean;
            id: string;
            lib: string;
            name: string;
            path?: string | null;
            reasons: string[];
            /** Format: int32 */
            score: number;
            signals: components["schemas"]["PosterSignal"][];
            tmdb: string;
            type: string;
        };
        RunScheduleResponse: {
            task: components["schemas"]["TaskRun"];
            /** Format: uuid */
            tid: string;
        };
        ScanLibraryItemResult: {
            /** Format: int32 */
            code: number;
            id?: string | null;
            name: string;
        };
        ScanLibraryRequest: {
            full?: boolean | null;
            item_id?: string | null;
            lib?: string | null;
            recursive?: boolean | null;
        };
        ScanLibraryResult: {
            global_refresh: boolean;
            items: components["schemas"]["ScanLibraryItemResult"][];
            mode: string;
            ok: boolean;
            requested?: string | null;
            triggered: number;
        };
        ScheduleInsight: {
            /** Format: int64 */
            enabled: number;
            /** Format: int64 */
            last_errors: number;
            /** Format: int64 */
            total: number;
        };
        ScheduleJob: {
            /** Format: date-time */
            created_at: string;
            enabled: boolean;
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: date-time */
            last_ended_at?: string | null;
            last_error?: string | null;
            /** Format: date-time */
            last_run_at?: string | null;
            last_status?: string | null;
            /** Format: uuid */
            last_task_id?: string | null;
            name: string;
            params: unknown;
            schedule: unknown;
            /** Format: date-time */
            updated_at: string;
        };
        ScheduleRequest: {
            enabled?: boolean | null;
            kind: string;
            name: string;
            params?: unknown;
            schedule: unknown;
        };
        ShareUrl: {
            pwd?: string | null;
            url: string;
        };
        StrmEntry: {
            is_dir: boolean;
            name: string;
            rel_path: string;
            /** Format: int64 */
            size: number;
        };
        StrmListResponse: {
            base: string;
            items: components["schemas"]["StrmEntry"][];
            overview?: null | components["schemas"]["StrmOverview"];
            truncated: boolean;
        };
        StrmOverview: {
            base: string;
            directories: number;
            entry_limit: number;
            files: number;
            max_depth: number;
            other_files: number;
            samples: components["schemas"]["StrmSample"][];
            /** Format: int64 */
            strm_bytes: number;
            strm_files: number;
            /** Format: int64 */
            subtitle_bytes: number;
            subtitle_extensions: components["schemas"]["ExtensionCount"][];
            subtitle_files: number;
            truncated: boolean;
            warnings: string[];
        };
        StrmReadOnlyOverview: {
            /** Format: int64 */
            directories: number;
            /** Format: int64 */
            empty_directories: number;
            entry_limit: number;
            exists: boolean;
            extension_counts: components["schemas"]["ExtensionCount"][];
            /** Format: int64 */
            files: number;
            is_dir: boolean;
            max_depth: number;
            /** Format: int64 */
            other_files: number;
            root: string;
            samples: components["schemas"]["StrmSignalSample"][];
            /** Format: int64 */
            strm_files: number;
            /** Format: int64 */
            subtitle_files: number;
            /** Format: int64 */
            top_level_dirs: number;
            truncated: boolean;
            warnings: string[];
        };
        StrmSample: {
            extension: string;
            kind: string;
            rel_path: string;
            /** Format: int64 */
            size: number;
        };
        StrmSignalSample: {
            kind: string;
            rel_path: string;
        };
        SystemSummary: {
            cd_root: string;
            cd_root_exists: boolean;
            configured_roots: components["schemas"]["PathStatus"][];
            database: components["schemas"]["DatabaseSummary"];
            docker_bin: string;
            docker_bin_exists: boolean;
            host: components["schemas"]["HostMetrics"];
            ok: boolean;
            rust_version: string;
            strm_root: string;
            strm_root_exists: boolean;
            version: string;
            warnings: string[];
        };
        TaskCancelResponse: {
            ok: boolean;
        };
        TaskHistorySummary: {
            /** Format: int64 */
            cancelled: number;
            /** Format: int64 */
            done: number;
            /** Format: int64 */
            error: number;
            /** Format: int64 */
            interrupted: number;
            /** Format: date-time */
            last_updated_at?: string | null;
            /** Format: int64 */
            pending: number;
            recent_issues: components["schemas"]["TaskIssue"][];
            /** Format: int64 */
            running: number;
            /** Format: int64 */
            stale_running: number;
            /** Format: int64 */
            total: number;
        };
        TaskIssue: {
            /** Format: uuid */
            id: string;
            kind: string;
            label: string;
            message: string;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        TaskListResponse: {
            /** Format: int64 */
            active_count: number;
            tasks: components["schemas"]["TaskRun"][];
        };
        TaskRun: {
            cancel_requested: boolean;
            /** Format: date-time */
            ended_at?: string | null;
            error?: string | null;
            /** Format: uuid */
            id: string;
            kind: string;
            label: string;
            params: unknown;
            /** Format: int64 */
            progress: number;
            /** Format: date-time */
            queued_at: string;
            result?: unknown;
            source: string;
            /** Format: date-time */
            started_at?: string | null;
            status: string;
            status_text: string;
            /** Format: int64 */
            total: number;
            /** Format: date-time */
            updated_at: string;
        };
        UndoEntry: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            legacy_id?: string | null;
            op: string;
            payload: unknown;
            undone: boolean;
        };
        /** @enum {string} */
        UndoExecuteAction: "manual_restore" | "pending_port" | "already_undone" | "unsupported";
        UndoExecuteRequest: {
            /** Format: uuid */
            id: string;
        };
        UndoExecuteResponse: {
            action: components["schemas"]["UndoExecuteAction"];
            folder?: string | null;
            hint?: string | null;
            /** Format: uuid */
            id: string;
            lib?: string | null;
            msg: string;
            ok: boolean;
            op: string;
        };
        UndoListQuery: {
            /** Format: int64 */
            limit?: number | null;
        };
        UndoListResponse: {
            items: components["schemas"]["UndoEntry"][];
            total: number;
        };
        UpdateUserPolicyRequest: {
            disabled?: boolean | null;
            /** Format: double */
            remote_bitrate_mbps?: number | null;
            /** Format: int64 */
            simultaneous_stream_limit?: number | null;
        };
        UpdateUserPolicyResponse: {
            ok: boolean;
            user: components["schemas"]["UserSummary"];
        };
        UserPolicySummary: {
            /** Format: int64 */
            RemoteClientBitrateLimit?: number | null;
            /** Format: int64 */
            SimultaneousStreamLimit?: number | null;
        };
        UserSummary: {
            disabled: boolean;
            id: string;
            last_activity_date?: string | null;
            name: string;
            policy: components["schemas"]["UserPolicySummary"];
            /** Format: double */
            remote_bitrate_mbps?: number | null;
        };
        UsersResponse: {
            users: components["schemas"]["UserSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    autostrm_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutostrmStatusResponse"];
                };
            };
        };
    };
    auto_cid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["C115AutoCidRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["C115AutoCidResponse"];
                };
            };
        };
    };
    offline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["C115OfflineRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    parse_url: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareUrl"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["C115ParseResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["C115SaveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    snap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["C115SnapRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["C115SnapResponse"];
                };
            };
        };
    };
    test_cookie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["C115TestResponse"];
                };
            };
        };
    };
    catalog_search: {
        parameters: {
            query: {
                q: string;
                limit?: number | null;
                link_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSearchResponse"];
                };
            };
        };
    };
    catalog_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogStatsResponse"];
                };
            };
        };
    };
    catalog_transfer_plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogTransferPlanRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogTransferPlanResponse"];
                };
            };
        };
    };
    cleanup_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupSummaryResponse"];
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    put_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    gaps_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapsSummaryResponse"];
                };
            };
        };
    };
    libraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrariesResponse"];
                };
            };
        };
    };
    scan_library: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanLibraryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    list_strm: {
        parameters: {
            query?: {
                lib?: string | null;
                folder?: string | null;
                limit?: number | null;
                overview?: boolean | null;
                overview_depth?: number | null;
                sample_limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrmListResponse"];
                };
            };
        };
    };
    list_logs: {
        parameters: {
            query?: {
                limit?: number | null;
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogListResponse"];
                };
            };
        };
    };
    preview_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManageDeleteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    preview_move: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManageMoveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    list_undo: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoListResponse"];
                };
            };
        };
    };
    exec_undo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UndoExecuteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoExecuteResponse"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PosterApplyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterApplyResponse"];
                };
            };
        };
    };
    detect_mismatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PosterDetectRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterDetectResponse"];
                };
            };
        };
    };
    fix_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PosterFixBatchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PosterSearchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterSearchResponse"];
                };
            };
        };
    };
    list_schedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleJob"][];
                };
            };
        };
    };
    create_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleJob"];
                };
            };
        };
    };
    update_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleJob"];
                };
            };
        };
    };
    delete_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteScheduleResponse"];
                };
            };
        };
    };
    run_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunScheduleResponse"];
                };
            };
        };
    };
    system_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSummary"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    demo_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoTaskRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
        };
    };
    cancel_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCancelResponse"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersResponse"];
                };
            };
        };
    };
    get_user_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emby user id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
    update_user_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emby user id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPolicyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateUserPolicyResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
