use crate::{
    api::{HealthResponse, PlaceholderResponse},
    auth::{LoginRequest, LoginResponse, MeResponse},
    c115::{
        C115AutoCidRequest, C115AutoCidResponse, C115CidMatch, C115DirEntry, C115OfflineRequest,
        C115OfflineResponse, C115ParseResponse, C115SaveRequest, C115SaveResponse,
    },
    c115::{C115SnapFile, C115SnapRequest, C115SnapResponse, C115TestResponse, ShareUrl},
    catalog::{
        CatalogC115OfflinePayload, CatalogC115OfflinePlan, CatalogC115SavePayload,
        CatalogC115SavePlan, CatalogDuplicateGroup, CatalogDuplicateQuery,
        CatalogDuplicatesResponse, CatalogLinkTypeCount, CatalogSearchQuery, CatalogSearchResponse,
        CatalogStatsResponse, CatalogTransferAction, CatalogTransferPlanItem,
        CatalogTransferPlanRequest, CatalogTransferPlanResponse, CatalogTransferTarget,
        CatalogUnsupportedPlan,
    },
    config_store::{ConfigResponse, ConfigUpdateRequest},
    emby::EmbyLibrary,
    gaps::{GapsScanLibRequest, GapsScanLibResult, GapsScanRow, SeasonGaps, SeriesGaps},
    insights::{
        AutostrmLibraryStat, AutostrmSeenStats, AutostrmSnapshot, AutostrmStatusResponse,
        AutostrmUnmatchedStats, CatalogInsight, CleanupSummaryResponse, ExtensionCount,
        GapsSummaryResponse, InsightMeta, InsightTodo, LogInsight, ScheduleInsight,
        StrmReadOnlyOverview, StrmSignalSample, TaskHistorySummary, TaskIssue,
    },
    logs::{AppLogEntry, LogListQuery, LogListResponse},
    media_fs::{
        LibrariesResponse, ManageDeleteExecuteResult, ManageDeleteRequest, ManageMoveRequest,
        ManagePreviewResult, ScanLibraryItemResult, ScanLibraryRequest, ScanLibraryResult,
        StrmEntry, StrmGenerateResult, StrmListResponse,
    },
    posters::{
        PosterApplyRequest, PosterApplyResponse, PosterDetectRequest, PosterDetectResponse,
        PosterFixBatchRequest, PosterFixBatchResult, PosterFixOneResult, PosterSearchCandidate,
        PosterSearchRequest, PosterSearchResponse, PosterSignal, PosterSignalItem,
    },
    scheduler::{DeleteScheduleResponse, RunScheduleResponse, ScheduleJob, ScheduleRequest},
    system::SystemSummary,
    tasks::{TaskCancelResponse, TaskListResponse, TaskRun},
    undo::{
        UndoEntry, UndoExecuteAction, UndoExecuteRequest, UndoExecuteResponse, UndoListQuery,
        UndoListResponse,
    },
    users::{
        UpdateUserPolicyRequest, UpdateUserPolicyResponse, UserPolicySummary, UserSummary,
        UsersResponse,
    },
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::api::health,
        crate::auth::login,
        crate::auth::logout,
        crate::auth::me,
        crate::config_store::get_config,
        crate::config_store::put_config,
        crate::tasks::list_tasks,
        crate::tasks::get_task,
        crate::tasks::cancel_task,
        crate::tasks::demo_task,
        crate::scheduler::list_schedules,
        crate::scheduler::create_schedule,
        crate::scheduler::update_schedule,
        crate::scheduler::delete_schedule,
        crate::scheduler::run_schedule,
        crate::catalog::catalog_stats,
        crate::catalog::catalog_search,
        crate::catalog::catalog_duplicates,
        crate::catalog::catalog_transfer_plan,
        crate::media_fs::libraries,
        crate::media_fs::scan_library,
        crate::media_fs::list_strm,
        crate::media_fs::preview_delete,
        crate::media_fs::execute_delete,
        crate::media_fs::preview_move,
        crate::posters::detect_mismatch,
        crate::posters::search,
        crate::posters::apply,
        crate::posters::fix_batch,
        crate::system::system_summary,
        crate::undo::list_undo,
        crate::undo::exec_undo,
        crate::logs::list_logs,
        crate::c115::test_cookie,
        crate::c115::parse_url,
        crate::c115::snap,
        crate::c115::save,
        crate::c115::offline,
        crate::c115::auto_cid,
        crate::insights::gaps_summary,
        crate::gaps::scan_library_gaps,
        crate::insights::cleanup_summary,
        crate::insights::autostrm_status,
        crate::users::list_users,
        crate::users::get_user_policy,
        crate::users::update_user_policy
    ),
    components(schemas(
        HealthResponse,
        PlaceholderResponse,
        LoginRequest,
        LoginResponse,
        MeResponse,
        ConfigResponse,
        ConfigUpdateRequest,
        TaskRun,
        TaskCancelResponse,
        TaskListResponse,
        ScheduleJob,
        ScheduleRequest,
        DeleteScheduleResponse,
        RunScheduleResponse,
        CatalogStatsResponse,
        CatalogDuplicateQuery,
        CatalogDuplicateGroup,
        CatalogLinkTypeCount,
        CatalogDuplicatesResponse,
        CatalogSearchQuery,
        CatalogSearchResponse,
        CatalogTransferAction,
        CatalogTransferPlanItem,
        CatalogTransferPlanRequest,
        CatalogTransferTarget,
        CatalogC115SavePayload,
        CatalogC115SavePlan,
        CatalogC115OfflinePayload,
        CatalogC115OfflinePlan,
        CatalogUnsupportedPlan,
        CatalogTransferPlanResponse,
        EmbyLibrary,
        LibrariesResponse,
        ScanLibraryRequest,
        ScanLibraryResult,
        ScanLibraryItemResult,
        StrmGenerateResult,
        ManageDeleteRequest,
        ManageDeleteExecuteResult,
        ManageMoveRequest,
        ManagePreviewResult,
        StrmEntry,
        StrmListResponse,
        PosterDetectRequest,
        PosterDetectResponse,
        PosterSignalItem,
        PosterSignal,
        PosterSearchRequest,
        PosterSearchResponse,
        PosterSearchCandidate,
        PosterApplyRequest,
        PosterApplyResponse,
        PosterFixBatchRequest,
        PosterFixBatchResult,
        PosterFixOneResult,
        SystemSummary,
        UndoEntry,
        UndoExecuteAction,
        UndoExecuteRequest,
        UndoExecuteResponse,
        UndoListQuery,
        UndoListResponse,
        AppLogEntry,
        LogListQuery,
        LogListResponse,
        ShareUrl,
        C115ParseResponse,
        C115TestResponse,
        C115SnapRequest,
        C115SnapFile,
        C115SnapResponse,
        C115SaveRequest,
        C115SaveResponse,
        C115OfflineRequest,
        C115OfflineResponse,
        C115AutoCidRequest,
        C115DirEntry,
        C115CidMatch,
        C115AutoCidResponse,
        InsightMeta,
        InsightTodo,
        GapsSummaryResponse,
        GapsScanLibRequest,
        GapsScanLibResult,
        GapsScanRow,
        SeriesGaps,
        SeasonGaps,
        CleanupSummaryResponse,
        AutostrmStatusResponse,
        TaskHistorySummary,
        TaskIssue,
        CatalogInsight,
        StrmReadOnlyOverview,
        ExtensionCount,
        StrmSignalSample,
        AutostrmSnapshot,
        AutostrmSeenStats,
        AutostrmUnmatchedStats,
        AutostrmLibraryStat,
        ScheduleInsight,
        LogInsight,
        UsersResponse,
        UserSummary,
        UserPolicySummary,
        UpdateUserPolicyRequest,
        UpdateUserPolicyResponse
    )),
    tags(
        (name = "health", description = "Runtime health"),
        (name = "auth", description = "Session and CSRF APIs"),
        (name = "config", description = "Settings APIs"),
        (name = "tasks", description = "Task center APIs"),
        (name = "schedules", description = "Scheduler APIs"),
        (name = "catalog", description = "115 catalog APIs"),
        (name = "media", description = "Media library APIs"),
        (name = "posters", description = "Poster detection APIs"),
        (name = "system", description = "System APIs"),
        (name = "undo", description = "Undo log APIs"),
        (name = "logs", description = "Application log APIs"),
        (name = "c115", description = "115 webapi APIs"),
        (name = "insights", description = "Read-only task and cleanup insights"),
        (name = "gaps", description = "Episode gap scanning APIs"),
        (name = "autostrm", description = "Auto STRM status APIs"),
        (name = "users", description = "Emby user policy APIs")
    )
)]
pub struct ApiDoc;
