use crate::{
    api::HealthResponse,
    auth::{
        ChangePasswordRequest, ChangePasswordResponse, LoginRequest, LoginResponse, MeResponse,
    },
    autostrm::{AutostrmTaskResult, AutostrmWebhookEvent, AutostrmWebhookResponse},
    c115::{
        C115AutoCidRequest, C115AutoCidResponse, C115CidMatch, C115DirEntry, C115OfflineRequest,
        C115OfflineResponse, C115ParseResponse, C115SaveRequest, C115SaveResponse,
    },
    c115::{
        C115SnapFile, C115SnapRequest, C115SnapResponse, C115TestCandidateRequest,
        C115TestResponse, ShareUrl,
    },
    catalog::{
        CatalogC115OfflinePayload, CatalogC115OfflinePlan, CatalogC115SavePayload,
        CatalogC115SavePlan, CatalogDuplicateGroup, CatalogDuplicateQuery,
        CatalogDuplicatesResponse, CatalogLinkTypeCount, CatalogSearchQuery, CatalogSearchResponse,
        CatalogStatsResponse, CatalogTransferAction, CatalogTransferExecuteRequest,
        CatalogTransferPlanItem, CatalogTransferPlanRequest, CatalogTransferPlanResponse,
        CatalogTransferTarget, CatalogUnsupportedPlan,
    },
    config_store::{
        ConfigImportRejected, ConfigImportReport, ConfigImportRequest, ConfigResponse,
        ConfigUpdateRequest,
    },
    dashboard::DashboardTodoResponse,
    dedup::{
        DedupAnalysisResponse, DedupAutoAllItemResult, DedupAutoAllRequest, DedupAutoAllResponse,
        DedupDeleteResult, DedupExecuteBatchGroup, DedupExecuteBatchItemResult,
        DedupExecuteBatchRequest, DedupExecuteBatchResult, DedupExecuteRequest,
        DedupExecuteResponse, DedupFolderRef, DedupGroup, DedupReviewGroup, DedupRow, EmbyUpdate,
        ReplaceBatchItemResult, ReplaceBatchRequest, ReplaceBatchResult, ReplaceExecuteResponse,
        ReplaceRequest,
    },
    emby::EmbyLibrary,
    gaps::{
        GapsScanLibRequest, GapsScanLibResult, GapsScanRow, SeasonGaps, SeriesGaps,
        SeriesGapsResponse,
    },
    insights::{
        AutostrmLibraryStat, AutostrmSeenStats, AutostrmSnapshot, AutostrmStatusResponse,
        AutostrmUnmatchedStats, CatalogInsight, CleanupCandidate, CleanupDimensionScore,
        CleanupSuggestRequest, CleanupSummaryResponse, EmptyDirCleanupRequest,
        EmptyDirCleanupResponse, EmptyDirCleanupTaskResult, EmptyFolderCandidate,
        EmptyFolderCleanupRequest, EmptyFolderCleanupTaskResult, ExtensionCount,
        GapsSummaryResponse, InsightMeta, InsightTodo, LogInsight, RefreshNoRatingRequest,
        RefreshNoRatingTaskItem, RefreshNoRatingTaskResult, ScheduleInsight, StrmReadOnlyOverview,
        StrmSignalSample, TaskHistorySummary, TaskIssue,
    },
    logs::{AppLogEntry, LogListQuery, LogListResponse},
    media_fs::{
        CreateLibraryRequest, CreateLibraryResponse, LibrariesResponse, LibraryItemEntry,
        LibraryItemsResponse, ManageDeleteBatchItemResult, ManageDeleteBatchRequest,
        ManageDeleteBatchResult, ManageDeleteExecuteResult, ManageDeleteRequest,
        ManageMoveBatchItem, ManageMoveBatchItemResult, ManageMoveBatchRequest,
        ManageMoveBatchResult, ManageMoveExecuteResult, ManageMoveRequest, ManagePreviewResult,
        ScanLibraryItemResult, ScanLibraryRequest, ScanLibraryResult, StrmEntry,
        StrmGenerateResult, StrmListResponse, SubtitleLanguageCount, SubtitleLibraryCoverage,
    },
    posters::{
        PosterApplyRequest, PosterApplyResponse, PosterDetectRequest, PosterDetectResponse,
        PosterFixBatchRequest, PosterFixBatchResult, PosterFixOneResult, PosterSearchCandidate,
        PosterSearchRequest, PosterSearchResponse, PosterSignal, PosterSignalItem,
        RefreshSeriesRequest, RefreshSeriesResponse,
    },
    scheduler::{DeleteScheduleResponse, RunScheduleResponse, ScheduleJob, ScheduleRequest},
    system::SystemSummary,
    tasks::{TaskCancelResponse, TaskListResponse, TaskRun},
    undo::{
        UndoEntry, UndoExecuteAction, UndoExecuteRequest, UndoExecuteResponse, UndoListQuery,
        UndoListResponse,
    },
    users::{
        CreateUserRequest, CreateUserResponse, DeleteUserResponse, UpdateUserPolicyRequest,
        UpdateUserPolicyResponse, UserPolicySummary, UserSummary, UsersResponse,
    },
    wizard::{
        AddNewCheckErrorReport, AddNewCheckItemReport, AddNewCheckReport,
        AddNewCheckSuspiciousReport, AddNewDedupReport, AddNewItem, AddNewPosterIssueReport,
        AddNewPosterReport, AddNewReport, AddNewRequest, AddNewScanReport, AddNewStrmReport,
        AddNewTarget, AddNewTargetReport, AddNewTransferAction, AddNewTransferItemReport,
        AddNewTransferSummary,
    },
    zhuigeng::{
        TmdbEpisodeSummary, ZhuigengGapRow, ZhuigengGapsSummaryResponse,
        ZhuigengGapsSummaryTaskResult, ZhuigengItem, ZhuigengScanAiringResponse,
        ZhuigengScanAiringRow, ZhuigengStatusResponse,
    },
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::api::health,
        crate::auth::login,
        crate::auth::logout,
        crate::auth::change_password,
        crate::auth::me,
        crate::autostrm::webhook,
        crate::config_store::get_config,
        crate::config_store::export_config,
        crate::config_store::put_config,
        crate::config_store::import_config,
        crate::tasks::list_tasks,
        crate::tasks::get_task,
        crate::tasks::cancel_task,
        crate::scheduler::list_schedules,
        crate::scheduler::create_schedule,
        crate::scheduler::update_schedule,
        crate::scheduler::delete_schedule,
        crate::scheduler::run_schedule,
        crate::dashboard::dashboard_todo,
        crate::catalog::catalog_stats,
        crate::catalog::catalog_search,
        crate::catalog::catalog_duplicates,
        crate::catalog::catalog_transfer_plan,
        crate::catalog::catalog_transfer_execute,
        crate::dedup::duplicates,
        crate::dedup::execute_dedup,
        crate::dedup::execute_dedup_batch,
        crate::dedup::replace_execute,
        crate::dedup::replace_batch,
        crate::dedup::auto_all,
        crate::media_fs::libraries,
        crate::media_fs::create_library,
        crate::media_fs::library_items,
        crate::media_fs::scan_library,
        crate::media_fs::list_strm,
        crate::media_fs::preview_delete,
        crate::media_fs::execute_delete,
        crate::media_fs::execute_delete_batch,
        crate::media_fs::preview_move,
        crate::media_fs::execute_move,
        crate::media_fs::execute_move_batch,
        crate::posters::detect_mismatch,
        crate::posters::search_query,
        crate::posters::search,
        crate::posters::apply,
        crate::posters::refresh_series,
        crate::posters::fix_batch,
        crate::system::system_summary,
        crate::undo::list_undo,
        crate::undo::exec_undo,
        crate::logs::list_logs,
        crate::c115::test_cookie,
        crate::c115::test_candidate_cookie,
        crate::c115::parse_url,
        crate::c115::snap,
        crate::c115::save,
        crate::c115::offline,
        crate::c115::auto_cid,
        crate::insights::gaps_summary,
        crate::gaps::scan_library_gaps,
        crate::gaps::series_gaps_detail,
        crate::insights::cleanup_summary,
        crate::insights::cleanup_empty_dirs,
        crate::insights::cleanup_empty_folders,
        crate::insights::refresh_no_rating,
        crate::insights::autostrm_status,
        crate::users::list_users,
        crate::users::create_user,
        crate::users::delete_user,
        crate::users::get_user_policy,
        crate::users::update_user_policy,
        crate::wizard::add_new,
        crate::zhuigeng::status,
        crate::zhuigeng::scan_airing,
        crate::zhuigeng::gaps_summary
    ),
    components(schemas(
        HealthResponse,
        LoginRequest,
        LoginResponse,
        MeResponse,
        ChangePasswordRequest,
        ChangePasswordResponse,
        AutostrmWebhookEvent,
        AutostrmWebhookResponse,
        AutostrmTaskResult,
        ConfigResponse,
        ConfigUpdateRequest,
        ConfigImportRequest,
        ConfigImportRejected,
        ConfigImportReport,
        TaskRun,
        TaskCancelResponse,
        TaskListResponse,
        ScheduleJob,
        ScheduleRequest,
        DeleteScheduleResponse,
        RunScheduleResponse,
        DashboardTodoResponse,
        CatalogStatsResponse,
        CatalogDuplicateQuery,
        CatalogDuplicateGroup,
        CatalogLinkTypeCount,
        CatalogDuplicatesResponse,
        CatalogSearchQuery,
        CatalogSearchResponse,
        CatalogTransferAction,
        CatalogTransferPlanItem,
        CatalogTransferPlanRequest,
        CatalogTransferExecuteRequest,
        CatalogTransferTarget,
        CatalogC115SavePayload,
        CatalogC115SavePlan,
        CatalogC115OfflinePayload,
        CatalogC115OfflinePlan,
        CatalogUnsupportedPlan,
        CatalogTransferPlanResponse,
        DedupRow,
        DedupGroup,
        DedupReviewGroup,
        DedupAnalysisResponse,
        DedupFolderRef,
        DedupExecuteRequest,
        DedupDeleteResult,
        DedupExecuteResponse,
        DedupExecuteBatchGroup,
        DedupExecuteBatchRequest,
        DedupExecuteBatchItemResult,
        DedupExecuteBatchResult,
        ReplaceRequest,
        EmbyUpdate,
        ReplaceExecuteResponse,
        ReplaceBatchRequest,
        ReplaceBatchItemResult,
        ReplaceBatchResult,
        DedupAutoAllRequest,
        DedupAutoAllItemResult,
        DedupAutoAllResponse,
        EmbyLibrary,
        LibrariesResponse,
        CreateLibraryRequest,
        CreateLibraryResponse,
        LibraryItemEntry,
        LibraryItemsResponse,
        ScanLibraryRequest,
        ScanLibraryResult,
        ScanLibraryItemResult,
        StrmGenerateResult,
        ManageDeleteRequest,
        ManageDeleteBatchRequest,
        ManageDeleteBatchResult,
        ManageDeleteBatchItemResult,
        ManageDeleteExecuteResult,
        ManageMoveRequest,
        ManageMoveExecuteResult,
        ManageMoveBatchItem,
        ManageMoveBatchRequest,
        ManageMoveBatchResult,
        ManageMoveBatchItemResult,
        ManagePreviewResult,
        StrmEntry,
        StrmListResponse,
        SubtitleLanguageCount,
        SubtitleLibraryCoverage,
        PosterDetectRequest,
        PosterDetectResponse,
        PosterSignalItem,
        PosterSignal,
        PosterSearchRequest,
        PosterSearchResponse,
        PosterSearchCandidate,
        PosterApplyRequest,
        PosterApplyResponse,
        RefreshSeriesRequest,
        RefreshSeriesResponse,
        PosterFixBatchRequest,
        PosterFixBatchResult,
        PosterFixOneResult,
        SystemSummary,
        UndoEntry,
        UndoExecuteAction,
        UndoExecuteRequest,
        UndoExecuteResponse,
        UndoListQuery,
        UndoListResponse,
        AppLogEntry,
        LogListQuery,
        LogListResponse,
        ShareUrl,
        C115ParseResponse,
        C115TestResponse,
        C115TestCandidateRequest,
        C115SnapRequest,
        C115SnapFile,
        C115SnapResponse,
        C115SaveRequest,
        C115SaveResponse,
        C115OfflineRequest,
        C115OfflineResponse,
        C115AutoCidRequest,
        C115DirEntry,
        C115CidMatch,
        C115AutoCidResponse,
        InsightMeta,
        InsightTodo,
        GapsSummaryResponse,
        GapsScanLibRequest,
        GapsScanLibResult,
        GapsScanRow,
        SeriesGaps,
        SeriesGapsResponse,
        SeasonGaps,
        CleanupSuggestRequest,
        CleanupSummaryResponse,
        CleanupCandidate,
        CleanupDimensionScore,
        EmptyDirCleanupRequest,
        EmptyDirCleanupResponse,
        EmptyDirCleanupTaskResult,
        EmptyFolderCleanupRequest,
        EmptyFolderCandidate,
        EmptyFolderCleanupTaskResult,
        RefreshNoRatingRequest,
        RefreshNoRatingTaskItem,
        RefreshNoRatingTaskResult,
        AutostrmStatusResponse,
        TaskHistorySummary,
        TaskIssue,
        CatalogInsight,
        StrmReadOnlyOverview,
        ExtensionCount,
        StrmSignalSample,
        AutostrmSnapshot,
        AutostrmSeenStats,
        AutostrmUnmatchedStats,
        AutostrmLibraryStat,
        ScheduleInsight,
        LogInsight,
        UsersResponse,
        UserSummary,
        UserPolicySummary,
        CreateUserRequest,
        CreateUserResponse,
        UpdateUserPolicyRequest,
        UpdateUserPolicyResponse,
        DeleteUserResponse,
        AddNewRequest,
        AddNewItem,
        AddNewTarget,
        AddNewReport,
        AddNewTargetReport,
        AddNewTransferSummary,
        AddNewTransferItemReport,
        AddNewTransferAction,
        AddNewStrmReport,
        AddNewDedupReport,
        AddNewScanReport,
        AddNewPosterReport,
        AddNewPosterIssueReport,
        AddNewCheckReport,
        AddNewCheckItemReport,
        AddNewCheckErrorReport,
        AddNewCheckSuspiciousReport,
        ZhuigengStatusResponse,
        ZhuigengItem,
        TmdbEpisodeSummary,
        ZhuigengScanAiringResponse,
        ZhuigengScanAiringRow,
        ZhuigengGapsSummaryResponse,
        ZhuigengGapsSummaryTaskResult,
        ZhuigengGapRow
    )),
    tags(
        (name = "health", description = "Runtime health"),
        (name = "auth", description = "Session and CSRF APIs"),
        (name = "config", description = "Settings APIs"),
        (name = "tasks", description = "Task center APIs"),
        (name = "schedules", description = "Scheduler APIs"),
        (name = "dashboard", description = "Dashboard parity APIs"),
        (name = "catalog", description = "115 catalog APIs"),
        (name = "media", description = "Media library APIs"),
        (name = "posters", description = "Poster detection APIs"),
        (name = "system", description = "System APIs"),
        (name = "undo", description = "Undo log APIs"),
        (name = "logs", description = "Application log APIs"),
        (name = "c115", description = "115 webapi APIs"),
        (name = "insights", description = "Read-only task and cleanup insights"),
        (name = "gaps", description = "Episode gap scanning APIs"),
        (name = "autostrm", description = "Auto STRM status APIs"),
        (name = "users", description = "Emby user policy APIs"),
        (name = "dedup", description = "Duplicate detection and replacement APIs"),
        (name = "wizard", description = "One-shot add-new-resource APIs"),
        (name = "zhuigeng", description = "Airing series and TMDb gap APIs")
    )
)]
pub struct ApiDoc;
